version: '3.6'

services:
  screenshotconsole:
    image: ${DOCKER_REGISTRY-}screenshotconsole
    build:
      context: .
      dockerfile: WebScreenShotApp\Dockerfile
    volumes:
      - type: bind
        source: C:/ScreenShot
        target: C:/ScreenShot

  screenshotservice:
    image: ${DOCKER_REGISTRY-}screenshotservice
    build:
      context: .
      dockerfile: ScreenShotService\Dockerfile
    volumes:
      - type: bind
        source: C:/ScreenShot
        target: C:/ScreenShot